### ISSUE TITLE
issue on deployment

### ISSUE THREAD

**Issue by shinykun** [ibenbouzid/SkypeforBusiness_lab_V3#1]
i had an issue when it tried to add AD user, here the issue : "VM has reported a failure when processing extension 'Add-ADUsers'. Error message.
do you have this issue? it installed the first vm and blocked on this

**Comment by ibenbouzid** [comment]
Hi,
Don't have this issue.
Could you check on your azure tenant the the vm name of 'VM-SFB-AD01' click on extensions then check the status of the 'Add-ADUsers' extension, you will find more details about the error you can also past it to here.

**Comment by shinykun** [comment]
i found the issue my password started with a "&", it blocked the user creation. the script continue now. I will let you know :)
