### ISSUE TITLE
There was an error loading the template

### ISSUE THREAD

**Issue by hotline007** [ibenbouzid/SkypeforBusiness_lab_V3#6]
When Click the "Deploy to Azure" button this error appears,
"There was an error loading the template from URI 'https://raw.githubusercontent.com/ibenbouzid/SkypeforBusiness_lab_V3/master/azuredeploy.json'. Ensure that the template is publicly accessible and does not have any comments.
"

thanks in advance

**Comment by Latheeshkumar** [comment]
Any solution for this issue ?

**Comment by hotline007** [comment]
I have contacted the author and unfortunately, he didn't have time to debug it again
